# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  #annotations:
    #deployment.kubernetes.io/revision: "1"
  #creationTimestamp: 2017-07-20T10:04:41Z
  #generation: 6
  labels:
    run: metis-microservice
  name: metis-microservice
  namespace: preprod
  #resourceVersion: "10253"
  #selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/php-apache
  #uid: d92d6904-6d32-11e7-b0df-0273cb8a0d13
spec:
  replicas: 1
  selector:
    matchLabels:
      run: metis-microservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      #creationTimestamp: null
      labels:
        run: metis-microservice
    spec:
      containers:
      - image: ameetkacr.azurecr.io/metis_api_preprod
      #- image: ameetk/nextquestions_preprod
        imagePullPolicy: Always
        name: metis-microservice-container
        ports:
        - containerPort: 80
          protocol: TCP
          #livenessProbe:
          #httpGet:
          #path: /user_ms/healthcheck
          # port: 80
          #initialDelaySeconds: 5
          #periodSeconds: 5
          #timeoutSeconds: 1
          #readinessProbe:
          #httpGet:
          #path: /user_ms/healthcheck
          #port: 80
          #initialDelaySeconds: 5
          #periodSeconds: 5
          #timeoutSeconds: 1
        resources:
          limits:
            cpu: 2
          requests:
            cpu: 1
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
      #imagePullSecrets:
      #- name: aks-container-sp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  name: metis-microservice
#  annotations: service.beta.kubernetes.io/aws-load-balancer-internal : "0.0.0.0/0"
  namespace: preprod
 # labels:
 #   dns: route53
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/user_ms/metrics'
    prometheus.io/port: '80'
#    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  #  service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'    # to create internal ELB
  #  domainName: "user-microservice.rearch.kubernetes.embibe.com,user-microservice.rearch.kubernetes.embibe.internal"
   # external-dns.alpha.kubernetes.io/hostname: "user.rearch.ap-southeast-1.elb.amazonaws.com"
spec:
#  type: LoadBalancer
  type: NodePort
 # clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: user-microservice
 # sessionAffinity: None
---
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: metis-microservice
  namespace: preprod
spec:
  maxReplicas: 100
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: metis-microservice
  targetCPUUtilizationPercentage: 80